version: '3'

services:
  api:
    container_name: ${APP_NAME}_api
    build: .
    restart: always
    environment:
      NODE_ENV: development
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: db
      DB_PORT: 5432
      DB_DIALECT: postgres
    ports:
      - 80:5000
    links:
      - db

  db:
    container_name: ${APP_NAME}_postgres
    image: postgres
    restart: always
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
