@startuml user signup
title User Signup Flow v2
hide footbox

UserRouter -> ValidationMiddleware ++: POST/user
ValidationMiddleware -> ValidationMiddleware ++--: validate
ValidationMiddleware --> UserRouter --: validatedUser

UserRouter -> UserController ++ : user(validatedUser)

group withTransactions
  UserController -> UserService ++: createUser(validatedUser)
  UserService -> UserRepository ++: createUser(validatedUser)
  UserRepository -> UserService --: user
  UserService -> UserController --: user

  UserController -> UserService ++: createConfirmationUserToken(user)
  UserService -> UserRepository ++: createUserToken(usr)
  UserRepository -> UserService --: userToken
  UserService -> UserController --: userToken
  group if user need change password
    UserController -> UserService ++: createPasswordUserToken(user)
    UserService -> UserRepository ++: createUserToken(user)
    UserRepository -> UserService --: userToken
    UserService -> UserController --: userToken
  end
end

UserController -> UserRouter : newUser

@enduml

@startuml user confirm
title User Confirmation Flow v1
hide footbox

UserRouter -> ValidationMiddleware ++: POST/user/confirm
ValidationMiddleware -> ValidationMiddleware ++--: validate
ValidationMiddleware --> UserRouter --: validatedUserToken

UserRouter -> UserController ++ : confirm(validatedUserToken)

UserController -> UserService ++: confirmUserAccount(validatedUserToken)
UserService -> UserRepository ++: getAndValidateUserToken(validatedUserToken)
UserRepository -> UserService --: validToken

group withTransaction
  UserService -> UserRepository : confirmUserToken(validToken)
  UserRepository -> UserRepository ++--: deleteUserToken
  UserRepository -> UserRepository ++--: updateUser
  UserRepository -> UserService : confirmed
end
UserService -> UserController --: confirmed

UserController -> UserRouter : confirmed

@enduml

@startuml user set password
title User Change Password Flow v1
hide footbox

UserRouter -> ValidationMiddleware ++: POST/user/password
ValidationMiddleware -> ValidationMiddleware ++--: validate
ValidationMiddleware --> UserRouter --: validatedUserToken

UserRouter -> UserController ++ : setPassword(validatedUserToken)

UserController -> UserService ++: setUserPassword(validToken)
UserService -> UserRepository ++: getAndValidateUserToken(validatedUserToken)
UserRepository -> UserService --: validToken

group withTransaction
  UserService -> UserRepository : setPasswordWithUserToken(validatedUserToken)
  UserRepository -> UserRepository ++--: deleteUserToken
  UserRepository -> UserRepository ++--: updateUser
  UserRepository -> UserService : updated
end
UserService -> UserController --: updated

UserController -> UserRouter : updated

@enduml

@startuml users list
title Users List Flow v2
hide footbox

UserRouter -> AuthMiddleware ++: GET /users
AuthMiddleware -> AuthMiddleware ++--: validate
AuthMiddleware --> UserRouter --: authenticated

UserRouter -> UserController ++ : users(filter)

UserController -> UserService ++: getAllUsers(filter)
UserService -> UserRepository ++: getAllUsers(filter)
UserRepository -> UserService --: users
UserService -> UserController --: users

UserController -> UserRouter : users

@enduml

@startuml delete user
title Delete User Flow v2
hide footbox

UserRouter -> AuthMiddleware ++: DELETE /user/:userId
AuthMiddleware -> AuthMiddleware ++--: validate
AuthMiddleware --> UserRouter --: authenticated

UserRouter -> UserController ++ : _delete(userId)

UserController -> UserService ++: deleteUser(filter)
group withTransaction
UserService -> UserRepository ++: deleteUser(filter)
UserRepository -> UserRepository ++--: deleteUser
UserRepository -> UserRepository ++--: deleteUserToken
UserRepository -> UserService --:
end
UserService -> UserController --:

UserController -> UserRouter :

@enduml

@startuml update user
title Update User Flow v2
hide footbox
participant UserRouter order 1
participant AuthMiddleware order 2
participant ValidateMiddleware order 3
participant UserController order 4
participant UserService order 5
participant UserRepository order 6

UserRouter -> AuthMiddleware ++: PUT /user/:userId
AuthMiddleware -> AuthMiddleware ++--: validate
AuthMiddleware --> UserRouter --: authenticated

UserRouter -> UserController ++ : update(user)

UserController -> UserService ++: updateUser(user)
UserService -> UserRepository ++: update(user)
UserRepository -> UserService --: updatedUser
UserService -> UserController --: updatedUser
UserController -> UserRouter --: updatedUser

== Enable/Disable User ==

UserRouter -> AuthMiddleware ++: POST /user/enable
AuthMiddleware -> AuthMiddleware ++--: validate
AuthMiddleware --> UserRouter --: authenticated

UserRouter -> ValidateMiddleware ++: validateParams
ValidateMiddleware -> ValidateMiddleware ++--: validate
ValidateMiddleware --> UserRouter --: valid

UserRouter -> UserController ++ : enable(params)

UserController -> UserService ++: setEnableUser(params)
UserService -> UserRepository ++: update(user)
UserRepository -> UserService --: updatedUser
UserService -> UserController --: updatedUser
UserController -> UserRouter : updatedUser

@enduml